### ISSUE TITLE
Support for `additionalProperties` -> `blackbox: true`?

### ISSUE THREAD

**Issue by chmac** [Yodata/meteor-json-simple-schema#11]
Firstly, thanks for this package, it's a huge contribution to the meteor space. Saves us a huge amount of headache.

Is there any way support for the `additionalProperties` flag translated into a `blackbox: true` in simple schema? We're using the generate props function and then adding the `blackbox` manually, so it's only a nice to have feature request. :-)

**Comment by bshamblen** [comment]
@chmac It doesn't sound like a complicated change, but I'll need to write a few tests to make sure it doesn't break anything in the process. I'll take a look at it tomorrow and let you know when it's done.

**Comment by chmac** [comment]
~~I'll try this nvm trick to see if I can get the tests running here. Then maybe I could lend a hand.~~

Confused about which repo I was posting on! I'm happy to try and lend a hand if you can point me in the right direction...
