### ISSUE TITLE
Autoform optional

### ISSUE THREAD

**Issue by rhythnic** [Yodata/meteor-json-simple-schema#2]
Including a 'afFieldInput' property in the simple schema when autoform is not installed causes simple schema to throw an error.  How about making autoform an option?

Great job on this package.  It's really needed.

**Comment by bshamblen** [comment]
Good catch. I'd just assumed that most people would use it with autoform. I'll add a check to make sure autoform is installed before adding that property. Thanks!

**Comment by rhythnic** [comment]
I've been playing around with checking for AutoForm like this:

```
if (Meteor.isClient && 'aldeed:autoform' in Package) {
```

The issue is with the package load order.  There's no way that I know of in Meteor to ensure package load order without declaring a dependency, which would install AutoForm.  Until Meteor has a better way to test for the installation of other packages, I don't see anything wrong with just doing api.use('aldeed:autoform'), since it'll be installed most of the time anyway, or make it an option.

**Comment by bshamblen** [comment]
Thanks for the pull request. I've merged your changes. I'll update the version number and publish the package later today.
