### ISSUE TITLE
enums with null

### ISSUE THREAD

**Issue by rhythnic** [Yodata/meteor-json-simple-schema#6]
Autoform is throwing an error on a converted JSON schema with null as an item in an enum.  To fix it, I'm removing null from the enum while converting it, and changing the '(Select One)' text to '(None)' to indicate that none is a valid option.

```
// in addRules function
if (source.enum) {
    target.allowedValues = source.enum.filter(function (item) {return item !== null; });
}
...
// in addAutoformAttributes function
if (source.enum && source.enum.some(function (item) { return item === null; })) {
    attachAutoformObject(target);
    target.autoform.afFieldInput.firstOption = '(None)';
}
```

**Comment by bshamblen** [comment]
I've integrated the suggested change to remove nulls from the enum list. I didn't add the block of code to automatically set the default first option to "(None)". I thought it would be best to leave it as the default "(Select One)".

**Comment by bshamblen** [comment]
Now that I think about it, I should probably add some logic to set the `firstOption` value to `(None)` if the property is not required. When the property is required it should still say `(Select One)`. I'll make a new issue for that.
