### ISSUE TITLE
Json schema sample

### ISSUE THREAD

**Issue by ouya99** [Yodata/meteor-json-simple-schema#9]
Hi, 

I followed your introduction to your package, but I have problems building up a schema, even using a very basic Json to parse - resulting in a parse error "SyntaxError: Unexpected token o"
Is this due to format problems

  var jsonSchemaDoc = JSON.parse({
    "id": 1,
    "name": "A green door",
    "price": 12.50,
    "tags": ["home", "green"]
});
    var jsonSchema = new JSONSchema(jsonSchemaDoc);
    var simpleSchema = jsonSchema.toSimpleSchema();
    console.log(simpleSchema);
    Contacts.attachSchema(simpleSchema);

Btw. What kind of json schema file do I require. Should I have a type field for each entry so that SimpleSchema will know the kind of "type"? see below. 
If not. How does your converter set the type?

```
"title": "Product set",
"type": "array",
"items": {
    "title": "Product",
    "type": "object",
    "properties": {
        "id": {
            "description": "The unique identifier for a product",
            "type": "number"
        },
        "name": {
            "type": "string"
        },
        "price": {
            "type": "number",
            "minimum": 0,
            "exclusiveMinimum": true
        },
```

Thanks
java99

**Comment by bshamblen** [comment]
The purpose of this package is to allow someone to convert pre-existing JSON Schema documents to to the SimpleSchema format. From the example you've included above, it looks like you're trying to pass in a basic JSON object, not a JSON Schema object.

The following is an example JSON Schema object that I'm using in my test code (mocha test): 

``` javascript
var jsonSchemaDoc = {
    '$schema': 'http://json-schema.org/draft-04/schema#',
    'title': 'Product',
    'description': 'A product from Acme\'s catalog',
    'type': 'object',
    'properties': {
        'id': {
            'description': 'The unique identifier for a product',
            'type': 'integer'
        },
        'name': {
            'description': 'Name of the product',
            'type': 'string'
        },
        'price': {
            'type': 'number',
            'minimum': '0', //test parsing of string values for number
            'exclusiveMinimum': 1 //test parsing string values for boolean
        },
        'tags': {
            'type': 'array',
            'items': {
                'type': 'string'
            },
            'minItems': 1,
            'uniqueItems': true
        },
        'arrayOfObjects': {
            'type': 'array',
            'items': {
                'type': 'object',
                'properties': {
                    'foo': {'type': 'string'}
                }
            }
        },
        'color': {
            'type': 'string',
            'enum': ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet', null]
        },
        'emailAddress': {
            'type': 'string',
            'format': 'email'
        }
    },
    'required': ['id', 'name', 'price']
};
```

For more examples and documentation of the JSON Schema specification, please refer to http://json-schema.org. If you're starting from scratch it's probably better to just build the schemas using the SimpleSchema spec, unless you have a need to share JSON Schema documents between Meteor and non-Meteor projects.

The converter will translate the `type` from the JSON Schema document to the corresponding SimpleSchema `type`. 

I also have a separate package ([json-schema-generator](https://atmospherejs.com/bshamblen/json-schema-generator)) which will take a JSON document and create a JSON Schema, but it only takes a best guess at the data types. You could use that package to create the `jsonSchemaDoc` object, then use the same code you have above to attach the schema to your collection.
